In [5]:
a = ['123-p01.png']

In [6]:
import numpy as np

In [9]:
axes_of_interest = np.unique(
            np.array([c.split("-")[1].split(".")[0][:-2] for c in a])
        )

In [10]:
axes_of_interest

array(['p'], dtype='<U1')

In [11]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9


In [5]:
import os
import numpy as np

In [6]:
dirname = "/home/namj/projects/ShapeYAnalysis/data/ShapeY200/dataset/"

In [7]:
imgnames = os.listdir(dirname)

In [10]:
objnames = list(np.unique([imgname.split("-")[0] for imgname in imgnames]))

In [11]:
import json

In [14]:
with open('ShapeY200_objs.json', 'w') as f:
    json.dump(objnames, f)

In [17]:
with open('../src/utils/ShapeY200_objs.json', 'r') as f:
    objs = json.load(f)


In [18]:
objs

['airplane_1021a0914a7207aff927ed529ad90a11',
 'airplane_326e859d86a8078427eb9e7911a17418',
 'airplane_35ae2885a0e645fb7843a50f3dd2047e',
 'airplane_53c7a6b56afb63807222da102ac36d2b',
 'airplane_7b134f6573e7270fb0a79e28606cb167',
 'airplane_844d36a369cdeed3ac4f72bf08dc79a6',
 'airplane_9513fcab860b113795ff232cd38210b4',
 'airplane_a28b92f0ed237d6d13256b8319a93100',
 'airplane_ecbb6df185a7b260760d31bf9510e4b7',
 'airplane_f7c2edc1beeedd006e68e46a69a2d96d',
 'bag_133c16fc6ca7d77676bb31db0358e9c6',
 'bag_151d033af5381fd4c1e1e64c8ea306ea',
 'bag_2ca6df7a5377825cfee773c7de26c274',
 'bag_39381a2718d2a1d4d5f008f38a566dee',
 'bag_4a1f62dbe8b091eabc49cae1a831a9e',
 'bag_74c548ef3ca7b1987515e7bb7dba4019',
 'bag_83ab18386e87bf4efef598dabc93c115',
 'bag_abba6df6294f20c569ea850160c0b35',
 'bag_adfe9029a1ca723eb8966aeece708f87',
 'bag_e90e27c3020d25dd76bb31db0358e9c6',
 'birdhouse_11dc4e10ef6e592f1aab8791875b3551',
 'birdhouse_2e81196fa81cc1fba29538f582b2005',
 'birdhouse_7bf5608a4d2c66bac5c86021644

In [1]:
import sys
sys.path.append("../src")
from utils.constants import SHAPEY200_IMGNAMES, SHAPEY200_OBJCATS

In [2]:
SHAPEY200_OBJCATS

array(['airplane', 'bag', 'birdhouse', 'boat', 'bunk bed', 'camera',
       'car', 'chair', 'faucet', 'guitar', 'headphone', 'lamp',
       'motorcycle', 'mug', 'pistol', 'pot', 'printer', 'rocket', 'sofa',
       'train'], dtype='<U10')

In [27]:
len(SHAPEY200_IMGNAMES)

68200

In [30]:
list1 = ["1", 2, 3, 4, 5]
list2 = [3, "4"]

if set(list2) <= set(list1):
    print("list2 is a subset of list1")
else:
    print("list2 is not a subset of list1")


list2 is not a subset of list1


In [1]:
import cupy as cp
import numpy as np

In [1]:
import sys
sys.path.append("../src")
from utils.constants import ALL_AXES
import utils
import numpy as np

In [2]:
cval_mat = np.full(
        [
            utils.NUMBER_OF_VIEWS_PER_AXIS,
            utils.NUMBER_OF_VIEWS_PER_AXIS * utils.NUMBER_OF_AXES,
        ],
        np.nan,
    )

In [7]:
print(cval_mat.itemsize * cval_mat.size)

30008


In [8]:
np.nan * 100

nan

In [6]:
d = np.random.random((11, 341))
print(d.itemsize)

8


In [4]:
contain_ax = cp.array(
    [
        [
            cp.array([c in a for c in 'p']).all()
            for a in ALL_AXES
        ]
    ],
    dtype=int,
)

In [12]:
contain_ax

array([[1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0]])

In [15]:
repeat_mask = contain_ax * contain_ax.T

In [16]:
repeat_mask.shape

(31, 31)

In [9]:
repeat_mask = cp.repeat(cp.repeat(repeat_mask, 11, axis=1), 11, axis=0)

In [11]:
repeat_mask

(341, 341)

In [18]:
import h5py

In [27]:
d = '/home/namj/projects/ShapeYTriad/data/processed/neural_net/xcit_large_24_p8_224_dist.h5'

In [28]:
a = h5py.File(d, 'r')

In [29]:
a.keys()

<KeysViewHDF5 ['feature_output', 'original', 'pairwise_correlation']>

In [36]:
a['original']['airplane_1021a0914a7207aff927ed529ad90a11/p/top1_cvals'].shape

(11, 11)

In [37]:
c = [1:10]

SyntaxError: invalid syntax (2212192611.py, line 1)

In [38]:
c = [range(1, 10)]

In [39]:
c

[range(1, 10)]

In [44]:
a['pairwise_correlation/original'][1:10,[2,5,9,11]].shape

(9, 4)

In [48]:
objidx = 1
whole_corrmat_idx = [
    objidx * utils.NUMBER_OF_VIEWS_PER_AXIS * utils.NUMBER_OF_AXES,
    (objidx + 1) * utils.NUMBER_OF_VIEWS_PER_AXIS * utils.NUMBER_OF_AXES,
]

In [49]:
whole_corrmat_idx

[341, 682]

In [54]:
whole_corrmat_idx_np = np.linspace(whole_corrmat_idx[0], whole_corrmat_idx[1]-1, whole_corrmat_idx[1]-whole_corrmat_idx[0], dtype=int)

In [55]:
whole_corrmat_idx_np

array([341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353,
       354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366,
       367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379,
       380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392,
       393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405,
       406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418,
       419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431,
       432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444,
       445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457,
       458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470,
       471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483,
       484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496,
       497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509,
       510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 52

In [77]:
contain_ax = np.array(
            [[all([c in a for c in 'pw'])]*11 for a in utils.ALL_AXES], dtype=int
        ).flatten()

In [79]:
contain_ax.shape

(341,)

In [62]:
whole_corrmat_idx_np.shape

(341,)

In [83]:
list(whole_corrmat_idx_np[contain_ax==1])

[363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648]

In [84]:
a = np.random.rand(1000, 1000)

In [87]:
a[[1,2,3],:].shape

(3, 1000)

In [7]:
from dataclasses import dataclass
from typing import Tuple, Union, Sequence, List
import typing
import numpy as np
import h5py
from abc import ABC
from bidict import bidict
import sys
sys.path.append("../src")
import utils


@dataclass
class CorrMat(ABC):
    description: 
    corrmat: Union[np.ndarray, h5py.Dataset]

    def __post_init__(self):
        assert self.corrmat.shape[0] == self.dims[0]
        assert self.corrmat.shape[1] == self.dims[1]


@dataclass
class WholeShapeYMat(CorrMat):
    def __post_init__(self):
        super().__post_init__()
        assert self.corrmat.shape[0] == len(utils.SHAPEY200_IMGNAMES)
        assert self.corrmat.shape[1] == len(utils.SHAPEY200_IMGNAMES)

@dataclass
class PartialCorrMat(CorrMat):
    shapey200_mapping: Tuple[
        Union[Sequence[str], Sequence[int]], Union[Sequence[str], Sequence[int]]
    ]  # describes the rows and columns of the input corrmat in ShapeY200 order

    def __post_init__(self):
        super().__post_init__()
        self.shapey200_mapping = PartialCorrMat.convert_mapping_to_int(
            self.shapey200_mapping
        )
        self.shapey200_mapping_dict = (
            bidict(enumerate(self.shapey200_mapping[0])),
            bidict(enumerate(self.shapey200_mapping[1])),
        )  # key: corrmat index, value: shapey200 index

    @staticmethod
    def convert_mapping_to_int(
        shapey200_mapping: Tuple[
            Union[Sequence[str], Sequence[int]], Union[Sequence[str], Sequence[int]]
        ]
    ) -> Tuple[Sequence[int], Sequence[int]]:
        row_descriptor, col_descriptor = shapey200_mapping

        if isinstance(row_descriptor[0], str):
            row_descriptor_idx = [
                utils.ImageNameHelper.imgname_to_shapey_idx(typing.cast(str, imgname))
                for imgname in row_descriptor
            ]
        else:
            row_descriptor_idx = typing.cast(List[int], row_descriptor)
        if isinstance(col_descriptor[0], str):
            col_descriptor_idx = [
                utils.ImageNameHelper.imgname_to_shapey_idx(typing.cast(str, imgname))
                for imgname in col_descriptor
            ]
        else:
            col_descriptor_idx = typing.cast(List[int], col_descriptor)

        return row_descriptor_idx, col_descriptor_idx



In [8]:
a = PartialCorrMat((1000, 1000), np.random.rand(1000, 1000), (range(1000), range(1000)))

In [12]:
a.corrmat.

(1000, 1000)

In [2]:
from typing import Sequence
def pull_axis_description_from_txt(filepath: str) -> Sequence[str]:
    with open(filepath, "r") as f:
        imgnames = f.read().splitlines()
    return imgnames

In [3]:
pull_axis_description_from_txt('../src/test/data_classes/imgnames_all.txt')

['features_airplane_1021a0914a7207aff927ed529ad90a11-p01.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p02.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p03.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p04.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p05.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p06.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p07.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p08.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p09.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p10.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-p11.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-pr01.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-pr02.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-pr03.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a11-pr04.mat',
 'features_airplane_1021a0914a7207aff927ed529ad90a1

In [4]:
import h5py

In [15]:
def h5_yield():
    with h5py.File('../src/test/test_data/distances.mat', 'r') as f:
        yield f


In [16]:
a = h5_yield()

In [19]:
c = a.__next__()

In [22]:
c['Jaccard_dist']

<HDF5 dataset "Jaccard_dist": shape (2200, 68200), type "<f4">

In [23]:
c.close()

In [1]:
from bidict import bidict

In [11]:
a = bidict({2:2, 1:4})

In [20]:
c = list(a.items())

In [21]:
c

[(2, 2), (1, 4)]

In [22]:
c.sort(key=lambda x: x[0])

In [23]:
d = [i[1] for i in c]

In [33]:
import cupy as cp
import numpy as np

In [38]:
a = []
a.append(cp.array([1,2,3]).get())
a.append(cp.array([4,5,6]).get())

In [43]:
b = np.array(a)

In [44]:
b[0,:]

array([1, 2, 3])

In [68]:
c = cp.array([[1,2,3], [np.nan,np.nan,np.nan]])

In [79]:
d=cp.nanmax(c, axis=1)

In [80]:
cp.isnan(d)

array([False,  True])

In [81]:
d[cp.isnan(d)] = -1

In [82]:
d

array([ 3., -1.])

In [71]:
e = np.zeros((2, 3), dtype=int)

In [72]:
e[:,0] = d

In [73]:
e

array([[                   3,                    0,                    0],
       [-9223372036854775808,                    0,                    0]])

In [64]:
e.dtype

dtype('int64')

In [83]:
e+1


array([[                   4,                    1,                    1],
       [-9223372036854775807,                    1,                    1]])

type(np.int)

In [84]:
type(np.float64)

type

In [1]:
import numpy as np
import cupy as cp

In [2]:
a = np.iinfo(np.uint8).max

In [6]:
a = np.array([1,2,3], dtype=np.uint8)

In [12]:
b = np.array([1,2,np.inf], dtype=float)

In [15]:
c = (a*b)

In [16]:
c.dtype

dtype('float64')

In [17]:
b.dtype

dtype('float64')

In [18]:
b[2] = a[1]

In [19]:
b

array([1., 2., 2.])

In [21]:
a[1] = c[2]

In [22]:
c

array([ 1.,  4., inf])

In [27]:
a[1] = c[2]

In [28]:
c[2]

inf

In [30]:
a[1]

0

In [37]:
a = a.astype(np.float64)

In [38]:
a[1]=c[2]

In [39]:
a

array([  1.,  inf, 255.])

In [4]:
import sys
sys.path.append("../")
import src.data_classes as dc
json_path = "../src/test/test_data/config_normal.json"
config = dc.NNAnalysisConfig.schema().loads(json_path)

ImportError: attempted relative import beyond top-level package