In [1]:
import numpy as np

In [5]:
a = np.random.rand(4000, 24) +1

In [6]:
b = a.astype(np.uint32)

In [7]:
b

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint32)

In [21]:
histcounts = np.apply_along_axis(
        lambda x: np.histogram(x, bins=np.linspace(0, 1, 1001))[0], 0, a
    )


In [22]:
histcounts.shape

(1000, 24)

In [23]:
d = np.cumsum(histcounts, axis=1)

In [25]:
d.shape

(1000, 24)

In [28]:
e = np.take(d, -1, axis=1)

In [29]:
np.allclose(e, d[:, -1])

True

In [1]:
import numpy as np

In [2]:
a = [np.zeros((1,1))]*3

In [4]:
a[0] = 1

In [5]:
a

[1, array([[0.]]), array([[0.]])]

In [6]:
a = np.random.random((3,5))

In [12]:
b = np.random.random((3,5))

In [13]:
c  = [a,b]

In [15]:
d = np.concatenate(c, axis=1)

In [16]:
d.shape

(3, 10)

In [17]:
a = [[]]*3

In [18]:
a

[[], [], []]

In [8]:
import os

In [9]:
a = os.listdir("/home/francis/nineCasesToRun")

In [11]:
a[:5]

['kernels16_poolingMap1Left2Right',
 'kernels12_poolingMap0Left1Right',
 'kernels12_poolingMap1Left1Right',
 'kernels24_poolingMap0Left1Right',
 'kernels24_poolingMap1Left1Right']

In [12]:
b = os.listdir(os.path.join("/home/francis/nineCasesToRun/", a[0]))

In [13]:
b

['poolingMap.mat',
 'kernels.mat',
 'konturs.lst',
 'triads.mat',
 'config.json',
 'features-results',
 'features-results-l2p1,2',
 'features-results-l2p0,1',
 'features-results-l2p1,1']

In [15]:
[fd for fd in os.listdir(os.path.join("/home/francis/nineCasesToRun/", a[0])) if "features-results-" in fd]

['features-results-l2p1,2',
 'features-results-l2p0,1',
 'features-results-l2p1,1']

In [16]:
a = [1,2,3,4,5,6]

In [18]:
a[:5]

[1, 2, 3, 4, 5]

In [19]:
a[5:]

[6]

In [25]:
import os
import shutil

In [21]:
dirname = '/home/francis/nineCasesToRun/'

In [22]:
thresholds = os.listdir('../thresholds/')

In [27]:
for th in thresholds:
    print(th)
    parsed_filename = th.split('_')
    kername = parsed_filename[0] + '_' + parsed_filename[1]
    features_dir = parsed_filename[2]
    filename = parsed_filename[3]
    print(os.path.join(dirname, kername, features_dir, filename))
    # shutil.copy(os.path.join('../thresholds/', th), os.path.join(dirname, kername, features_dir, filename))
    os.remove(os.path.join(dirname, kername, features_dir, filename))

kernels12_poolingMap1Left2Right_features-results-l2p1,2_thresholds.mat
/home/francis/nineCasesToRun/kernels12_poolingMap1Left2Right/features-results-l2p1,2/thresholds.mat
kernels16_poolingMap1Left2Right_features-results-l2p1,2_thresholds.mat
/home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p1,2/thresholds.mat
kernels16_poolingMap1Left1Right_features-results-l2p0,1_thresholds.mat
/home/francis/nineCasesToRun/kernels16_poolingMap1Left1Right/features-results-l2p0,1/thresholds.mat
kernels12_poolingMap1Left1Right_features-results-l2p1,1_thresholds.mat
/home/francis/nineCasesToRun/kernels12_poolingMap1Left1Right/features-results-l2p1,1/thresholds.mat
kernels24_poolingMap0Left1Right_features-results-l2p0,1_thresholds.mat
/home/francis/nineCasesToRun/kernels24_poolingMap0Left1Right/features-results-l2p0,1/thresholds.mat
kernels24_poolingMap1Left2Right_features-results-l2p1,2_thresholds.mat
/home/francis/nineCasesToRun/kernels24_poolingMap1Left2Right/features-resu

In [28]:
dirname

'/home/francis/nineCasesToRun/'

In [29]:
import json

In [30]:
with open('/home/francis/nineCasesToRun/kernels12_poolingMap1Left2Right/features-results-l2p1,2/config.json') as f:
    data = json.load(f)

In [31]:
data

{'featuresContourMatrixName': 'twelveChannelOrigLmax',
 'poolingKernelsFileName': '/home/francis/nineCasesToRun/kernels12_poolingMap1Left2Right/kernels.mat',
 'poolingKernelsMatrixName': 'kernels',
 'featuresL1PoolingNeighborsFileName': '/home/francis/nineCasesToRun/kernels12_poolingMap1Left2Right/poolingMap.mat',
 'featuresL1PoolingNeighborsMatrixName': 'poolingMap',
 'triadsFileName': '/home/francis/nineCasesToRun/kernels12_poolingMap1Left2Right/triads.mat',
 'triadsMatrixName': 'triads',
 'featuresL2PoolingLeftNeighbors': 1,
 'featuresL2PoolingRightNeighbors': 2}

In [ ]:
data["featuresThresholdsFileName"] = 

In [33]:
for kerdir in os.listdir(dirname):
    features_dir = [f for f in os.listdir(os.path.join(dirname, kerdir)) if 'features-results-' in f]
    for fd in features_dir:
        with open(os.path.join(dirname, kerdir, fd, 'config.json')) as f:
            configs = json.load(f)
        configs["featuresThresholdsFileName"] = os.path.join(dirname, kerdir, fd, 'thresholds.mat')
        with open(os.path.join(dirname, kerdir, fd, 'config.json'), 'w') as f:
            json.dump(configs, f)

dir = '/home/francis/nineCasesToRun/kernels12_poolingMap0Left1Right/features-results-l2p0,1'

In [34]:
d = '/home/francis/nineCasesToRun/kernels12_poolingMap0Left1Right/features-results-l2p0,1'

In [35]:
thres = os.path.join(d, 'thresholds.mat')

In [38]:
feat_file = os.listdir(d)[0]

In [39]:
feat_file

'features_guitar_da8ee6c488a2f4e093f806b1ecaee483-x06.mat'

In [36]:
import h5py

In [37]:
with h5py.File(thres, 'r') as f:
    print(list(f.keys()))

['features_threshold_0', 'features_threshold_1', 'features_threshold_2', 'features_threshold_3', 'features_threshold_4', 'features_threshold_5']


In [56]:
d = '/home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p1,2'
with h5py.File(os.path.join(d, feat_file), 'r') as hf:
    print(list(hf.keys()))
    data = hf['l2pool_0'][:]

['l2pool_0', 'l2pool_1', 'l2pool_2']


In [58]:
data.shape

(4000, 24)

In [54]:
import sys
sys.path.append('../')
import random
import shapeymodular.utils as utils
for kerdir in os.listdir(dirname):
    features_dir = [f for f in os.listdir(os.path.join(dirname, kerdir)) if 'features-results-' in f]
    for fd in features_dir:
        allfiles = os.listdir(os.path.join(dirname, kerdir, fd))
        features = []
        print("checking: {}".format(os.path.join(dirname, kerdir, fd)))
        for f in random.sample(allfiles, 1000):
            if ".mat" in f and "features_" in f:
                imgname = f.split("features_")[1].split(".mat")[0] + ".png"
                if imgname in utils.SHAPEY200_IMGNAMES:
                    features.append(f)
        for f in features:
            with h5py.File(os.path.join(dirname, kerdir, fd, f), 'r') as hf:
                if len(list(hf.keys())) != 6:
                    print(hf.keys())
                    print(os.path.join(dirname, kerdir, fd))
                    print("filename {}".format(f))
                    break
                elif "detected_0" not in list(hf.keys()):
                    print(os.path.join(dirname, kerdir, fd))
                    print("filename {}".format(f))
                    break

checking: /home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p1,2
<KeysViewHDF5 ['l2pool_0', 'l2pool_1', 'l2pool_2']>
/home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p1,2
filename features_mug_6aec84952a5ffcf33f60d03e1cb068dc-y06.mat
checking: /home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p0,1
checking: /home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p1,1
<KeysViewHDF5 ['l2pool_0', 'l2pool_1', 'l2pool_2']>
/home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p1,1
filename features_headphone_2b28e2a5080101d245af43a64155c221-xp07.mat
checking: /home/francis/nineCasesToRun/kernels12_poolingMap0Left1Right/features-results-l2p0,1
checking: /home/francis/nineCasesToRun/kernels12_poolingMap0Left1Right/features-results-l2p1,1
<KeysViewHDF5 ['l2pool_0', 'l2pool_1', 'l2pool_2']>
/home/francis/nineCasesToRun/kernels12_poolingMap0Left1Right/featu

In [1]:
d = '/home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p0,1'

In [3]:
import os
files = [f for f in os.listdir(d) if "features_" in f and "mat" in f]

In [6]:
import h5py
with h5py.File(os.path.join(d, files[0]), 'r') as hf:
    print(list(hf.keys()))
    print(os.path.join(d, files[0]))

['detected_0', 'detected_1', 'detected_2', 'l2pool_0', 'l2pool_1', 'l2pool_2']
/home/francis/nineCasesToRun/kernels16_poolingMap1Left2Right/features-results-l2p0,1/features_camera_c9c9ffd08af8b268b52759c2c2fc0d1e-xypr11.mat


In [7]:
f = '/home/namj/projects/ShapeYTriad/data/raw/diads12ChannelsRegularLmax/features-with-diads12ChannelsRegularLmax/features_airplane_7b134f6573e7270fb0a79e28606cb167-p01.mat'

In [8]:
with h5py.File(f, 'r') as hf:
    print(list(hf.keys()))

['subframe_0', 'subframe_1', 'subframe_2']


In [1]:
import h5py

In [61]:
v1_path ='/home/namj/projects/ShapeYV2/shapeymodular/test/test_data/cross_version_test_data/analysis_results_v1/diads12ChannelsRegularLmax-Jaccard_results.mat'
v2_path = '/home/namj/projects/ShapeYV2/shapeymodular/test/test_data/cross_version_test_data/analysis_results_v2/diads12ChannelsRegularLmax-Jaccard_results.h5'

In [63]:
hf.close()
hf_v2.close()

In [64]:
hf = h5py.File(v1_path, 'r')
hf_v2 = h5py.File(v2_path, 'r')

In [102]:
top1_cvals_otherobj_v2 = hf_v2['airplane_53c7a6b56afb63807222da102ac36d2b/pw/top1_cvals_otherobj'][:]
top1_idx_otherobj_v2 = hf_v2['airplane_53c7a6b56afb63807222da102ac36d2b/pw/top1_idx_otherobj'][:]

In [103]:
top1_cvals_otherobj_v1 = hf['original/airplane_53c7a6b56afb63807222da102ac36d2b/pw/top1_cvals_otherobj'][:]
top1_idx_otherobj_v1 = hf['original/airplane_53c7a6b56afb63807222da102ac36d2b/pw/top1_idx_otherobj'][:]

In [108]:
top1_cvals_otherobj_v1 = np.expand_dims(top1_cvals_otherobj_v1, axis=1)

In [111]:
not_equal_idxs = np.transpose(np.where(~np.isclose(top1_cvals_otherobj_v1, top1_cvals_otherobj_v2)))

In [114]:
for r, c, in not_equal_idxs:
    print(top1_cvals_otherobj_v1[r, c])
    print(top1_cvals_otherobj_v2[r, c])


nan
0.0


In [105]:
top1_idx_otherobj_v1

array([  802, 58013, 32878, 59002, 30628, 30386, 30386,  3079,  3079,
         130,   131])

In [106]:
top1_idx_otherobj_v2

array([[    0],
       [58013],
       [32878],
       [59002],
       [30628],
       [30386],
       [30386],
       [ 3079],
       [ 3079],
       [  130],
       [  131]])

In [91]:
top1_per_obj_v1 = hf['original/airplane_53c7a6b56afb63807222da102ac36d2b/pw/top1_per_obj_cvals'][:]
top1_per_obj_v2 = hf_v2['airplane_53c7a6b56afb63807222da102ac36d2b/pw/']['top1_per_obj_cvals'][:]

In [93]:
top1_per_obj_v1[0,:]

array([ 0.,  0., nan,  0., nan,  0.,  0., nan, nan,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., nan,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan, nan, nan,
       nan,  0., nan, nan, nan, nan, nan, nan,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., nan,  0., nan,
        0.,  0., nan,  0.,  0.,  0.,  0., nan,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
       nan,  0., nan, nan, nan, nan, nan, nan, nan,  0.,  0.,  0

In [94]:
top1_per_obj_v2[0,:]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [1]:
import sys
sys.path.append('../')
import shapeymodular.utils as utils

In [97]:
utils.SHAPEY200_OBJS.index('airplane_53c7a6b56afb63807222da102ac36d2b')

3

In [2]:
import numpy as np

In [8]:
in_same_objcat = np.array(
                    [
                        utils.ImageNameHelper.get_obj_category_from_objname(utils.SHAPEY200_OBJS[0])
                        == utils.ImageNameHelper.get_obj_category_from_objname(
                            other_obj
                        )
                        for other_obj in utils.SHAPEY200_OBJS
                        if other_obj != utils.SHAPEY200_OBJS[0]
                    ]
                )

In [9]:
in_same_objcat

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [10]:
same_obj_mask = np.tile(
                    in_same_objcat, (11, 1)
                )

In [12]:
same_obj_mask.shape

(11, 199)

In [1]:
import numpy as np

In [31]:
a = np.linspace(0, 10, 11)
b = np.linspace(0, 10, 11)
c = np.linspace(1, 11, 11)
d = [a, b, c]

In [40]:
m = np.mean(d, axis=0)

In [54]:
(((d-m)**2).sum(axis=0)/2)**0.5

array([0.57735027, 0.57735027, 0.57735027, 0.57735027, 0.57735027,
       0.57735027, 0.57735027, 0.57735027, 0.57735027, 0.57735027,
       0.57735027])

In [52]:
np.std(d, axis=0, ddof=1)

array([0.57735027, 0.57735027, 0.57735027, 0.57735027, 0.57735027,
       0.57735027, 0.57735027, 0.57735027, 0.57735027, 0.57735027,
       0.57735027])

In [45]:
np.sqrt((1-0.33333)**2+(-0.33333)**2 + (-0.33333)**2)/3

0.27216552698271285